name: "Test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit-2.1.0-beta3", "luajit-openresty"]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: true

    - uses: leafo/gh-actions-lua@6919171ccf181b826f44b9bca76307b577217377 # v13.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@35d062def313a7699a0d513e996bcf4352f05389 # v6.1.0

    - name: dependencies
      run: |
        luarocks install busted
        luarocks install luacov-coveralls

    - name: Execute tests
      run: |
        make test LUA_VER=""

    - name: Report test coverage
      if: success()
      continue-on-error: true
      run: luacov-coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ github.token }}